# Use the official Node.js LTS image as the base
FROM node:lts

# Create a directory to hold the application code
WORKDIR /app

# Copy package.json and package-lock.json to the work directory
COPY package*.json ./

# Install any needed packages
RUN npm install

# Bundle app source
COPY . .

# Expose the port the bank server will run on
EXPOSE 3000

# Start the bank server
CMD ["node", "startSecondBank.mjs"]